### ISSUE TITLE
非常好用！！！

### ISSUE THREAD

**Issue by Lukangkang123** [PairZhu/GPT-QQRobot#1]
没报错。如果私聊能直接对话就好了。还有，群聊有时候好像不管用

**Comment by PairZhu** [comment]
群聊不管用的截图给一下，我这里没遇到过

**Comment by PairZhu** [comment]
私聊直接回复我可以考虑设置个配置项

**Comment by Lukangkang123** [comment]
> 群聊不管用的截图给一下，我这里没遇到过

可以了可以了，原来群聊也得#gpt begin才能发起会话。感谢回复~

**Comment by PairZhu** [comment]
功能已加
