### ISSUE TITLE
DISABLE_PROMPT 没有用

### ISSUE THREAD

**Issue by zj0395** [PairZhu/GPT-QQRobot#10]
如题，设置了环境变量，依然会提示（对话已达到最大长度，将删除最早的一条对话）

**Comment by PairZhu** [comment]
压根没有这个配置项，你仔细看文档。必须有个max_prompts，disable_tips是用来关闭提示的，并不能无限长对话，你可以把这个值设置的非常大，但是api本身也有限制，prompts+回答的token数加起来不能超过4000，否则api会拒绝回复

**Comment by zj0395** [comment]
我就是想要取消这个提示；这写了 DISABLE_PROMPT；看代码里没处理这个环境变量
![image](https://user-images.githubusercontent.com/26669839/226090504-c8842aee-72ef-4af6-846d-83f9e9c15361.png)

**Comment by PairZhu** [comment]
我的我的，文档写错了

**Comment by PairZhu** [comment]
文档已修复，环境变量为NO_TIP
