### ISSUE TITLE
如果购买了plus之后，chatgpt4.0版本的能否正常使用呢？

### ISSUE THREAD

**Issue by MarcioXIN** [PairZhu/GPT-QQRobot#12]
如题，如果购买了plus之后，chatgpt4.0版本的能否正常使用呢？

**Comment by PairZhu** [comment]
这没啥联系啊，我这个用的3.5的接口，和4.0互不影响，等4.0接口彻底开放了，或者我拿到试用权限，我会加入4.0的选项

**Comment by MarcioXIN** [comment]
了解，我以为chatgpt版本只是openai账号的差别
