### ISSUE TITLE
如何自动同意qq好友申请

### ISSUE THREAD

**Issue by jiangsasa** [PairZhu/GPT-QQRobot#16]
qq群临时会话不能触发消息回复，需要添加好友才行

**Comment by PairZhu** [comment]
1. 不建议这么做，这样不方便管理用户，其它用户可以直接在群里使用，如果担心上下文受到影响可以把群聊模式改为personal模式
2. 如果非要这么做，这不属于本应用的范畴，可以自己开发一个插件连接到cq-http上进行对应的处理
