### ISSUE TITLE
通过Acccess_token 接入 slack-claude

### ISSUE THREAD

**Issue by xtchn** [PairZhu/GPT-QQRobot#17]
下面是参考代码 https://github.com/lss233/chatgpt-mirai-qq-bot/blob/browser-version/adapter/claude/slack.py 
https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/jie-ru-ai-ping-tai/jie-ru-claude

**Comment by xtchn** [comment]
大佬，能尝试适配下吗？

**Comment by PairZhu** [comment]
slack-claude和我这个代码的模型不兼容，要加入就等于开了新项目了。我这里面很多功能是claude是没办法支持的，这个项目主要是个人使用，也只有我一个人开发，没那么多精力处理那么多情况和支持，见谅
