### ISSUE TITLE
兼容API2D

### ISSUE THREAD

**Issue by liaojiankun** [PairZhu/GPT-QQRobot#18]
请问能否适配兼容API2D的api使用？直接将它加为第三方api中会报错。这个在国内使用和充值都相对便利一些。
这个是他们的网址 https://api2d.com/

**Comment by PairZhu** [comment]
国内的这种网站太多了，没办法都适配，所以暂时不考虑，如果做成可自己定制的那就需要开发基础，如果有这个基础了，那完全可以做到自己clone项目开发
