### ISSUE TITLE
api失效是不能用了吗呜呜

### ISSUE THREAD

**Issue by cjy4979** [PairZhu/GPT-QQRobot#2]
https://github.com/transitive-bullshit/chatgpt-api，老哥看看这个可行？

**Comment by PairZhu** [comment]
这个更不行，这个人家就是国外的项目，更不可能考虑国内的情况

**Comment by PairZhu** [comment]
用代理吧，代理最稳，我马上更新一下增加代理配置的选项

**Comment by PairZhu** [comment]
已经解决了，增加了代理配置，第三方接口也恢复了，并且还增加了一个新的
