### ISSUE TITLE
cqhttp通信成功，输入命令无反馈

### ISSUE THREAD

**Issue by AmamiyaHotaru** [PairZhu/GPT-QQRobot#4]
![image](https://user-images.githubusercontent.com/38397474/223749040-d086e6dc-901f-4b3d-b059-bc57c47905c6.png)
![image](https://user-images.githubusercontent.com/38397474/223749163-cd333778-6b5d-4fdf-a688-bfcf4abdc982.png)

**Comment by PairZhu** [comment]
终端日志上也没有显示收到消息吗

**Comment by AmamiyaHotaru** [comment]
> 

没有 日志内容就一直是这么几行了

**Comment by PairZhu** [comment]
确实很奇怪，你是用源码部署的还是docker部署的

**Comment by AmamiyaHotaru** [comment]
我都进行过尝试，结果一样，而且gocq的版本是最新的

**Comment by AmamiyaHotaru** [comment]
我下载了份win的gocq，拷贝一切正常，同局域网下fedora就不行，具体原因还没发现

**Comment by PairZhu** [comment]
会不会是和防火墙有关

**Comment by AmamiyaHotaru** [comment]
问题已经解决了，我把gocq配置文件、设备信息、session 全删除之后重新运行就好了，都不知道为什么会出现这么奇怪的问题

**Comment by YukisawaNya** [comment]
遇到了同样的问题，尝试删配置重新登录以及更换cqhttp的后端实现，均无效👀测试的设备没有开启任何防火墙👀
环境 Ubuntu 22.04.1 LTS
