### ISSUE TITLE
我还在回答上一个问题呢，请稍后再试

### ISSUE THREAD

**Issue by Lukangkang123** [PairZhu/GPT-QQRobot#5]
如果不用第三方的接口,j就会提示“我还在回答上一个问题呢，请稍后再试”。第三方接口还好用点，不过有时也会出现“出错了，请稍后再试，或联系管理员”，不知道这是什么原因呢？另外请问能不能把详细报错信息输出，这样都不知道哪儿出现问题了

**Comment by PairZhu** [comment]
这个提醒是正常输出啊，是同一个对话同一时间只能回答一个问题，是刻意为之的

**Comment by Lukangkang123** [comment]
> 这个提醒是正常输出啊，是同一个对话同一时间只能回答一个问题，是刻意为之的

只有我一个人问问题，没有同时对话

**Comment by PairZhu** [comment]
我没有做消息排队机制，我认为这是不符合对话直觉的，因为当两个人同时提问时，前一个人的回答完之后对话的上下文就变了

**Comment by PairZhu** [comment]
就是你在机器人回答完上一个问题之前就你说了下一句话

**Comment by PairZhu** [comment]
不是多少个人的问题

**Comment by PairZhu** [comment]
具体你可以发一下聊天记录

**Comment by Lukangkang123** [comment]
> 具体你可以发一下聊天记录
这是聊天记录，你看看。我是第一次提问就出现了这样的问题，也没有出现上一个问题之前我就说了下一句话的情况。
![(VDQIU43PN K7 765@8__SM](https://user-images.githubusercontent.com/38984189/223902366-14c24b6c-d3be-41f7-9c50-ba9decf7aadb.png)

**Comment by PairZhu** [comment]
因为它就是在回复你再之前的那个“你好”，在#gpt begin之前的那个，不过你已经开启新的对话了，理论上不该在等待了，这个算是个小bug可以修一下

**Comment by PairZhu** [comment]
你说的第三方接口好点，官方接口就更严重了，实际上就是响应速度的问题，应该是你的代理速度慢或者不通。所以响应时间非常长

**Comment by Lukangkang123** [comment]
> 

我开的代理，用命令行访问外网是正常的呀，速度也可以。感觉可能它访问openai接口的时候没用代理

**Comment by PairZhu** [comment]
请看配置文档里的代理配置

**Comment by PairZhu** [comment]
首先确保你在配置文件里配置了代理，然后确保你的代理规则命中了openai

**Comment by Lukangkang123** [comment]
> 首先确保你在配置文件里配置了代理，然后确保你的代理规则命中了openai
这个配置文件中的代理设置，是最近更新的吧。我下载后的，没这个设置

**Comment by PairZhu** [comment]
是的，昨天更新的

**Comment by PairZhu** [comment]
上面那个小bug已经修复了，你可以这会儿再重新拉一下最新的代码

**Comment by Lukangkang123** [comment]
> 上面那个小bug已经修复了，你可以这会儿再重新拉一下最新的代码

好的，我试试~

**Comment by Lukangkang123** [comment]
> 上面那个小bug已经修复了，你可以这会儿再重新拉一下最新的代码

用了新的代码，它提示“出错了，请稍后再试，或联系管理员”
![image](https://user-images.githubusercontent.com/38984189/223906298-81e64da9-a06b-46f2-82a9-0fa1287340a4.png)

**Comment by PairZhu** [comment]
那就是没走代理，并且没使用第三方接口

**Comment by Lukangkang123** [comment]
> 那就是没走代理，并且没使用第三方接口

没走代理的话，应该还是在等待回复呀，它这是直接报错了

**Comment by PairZhu** [comment]
没走代理就是会访问不通啊，访问不同就会抛出异常

**Comment by Lukangkang123** [comment]
> 

但是我已经开了代理，但是在配置文件中配置了，怎么会访问不通呢

**Comment by PairZhu** [comment]
请尝试切换为第三方api或者确保openai.com被代理规则命中了。以及部分太便宜的机场的代理一样是走不通的

**Comment by PairZhu** [comment]
具体你可以查看你代理软件的日志

**Comment by Lukangkang123** [comment]
可以了，感谢~
