### ISSUE TITLE
很棒，简约易上手，但群聊又不响应了

### ISSUE THREAD

**Issue by NyaaCaster** [PairZhu/GPT-QQRobot#6]
我用的docker方式搭建，服务器在海外，不适用代理，私聊很顺畅。
但群聊@无响应，日志也未见响应，如果有需要，可以加我的群我协助测试 741856032
另外我无法通过 docker exec -it 进入docker容易，请问如果要调整robot的内部配置，应该使用哪种方式？

**Comment by PairZhu** [comment]
请确认你拉取的镜像是最新版

**Comment by PairZhu** [comment]
理论上不需要exec进容器，所有的配置都在config下面，详情请看配置文档。如果一定要进去容易，请使用sh而不是bash，因为是最小镜像所以没有bash

**Comment by NyaaCaster** [comment]
> 是从docker hub拉取的pairzhu/gptrobot:latest，这个是最新版本吗

**Comment by NyaaCaster** [comment]
重新拉取了一次，确实有一个更新
感谢，已经解决了
