### ISSUE TITLE
出错了，请稍后再试，或联系管理员

### ISSUE THREAD

**Issue by Lukangkang123** [PairZhu/GPT-QQRobot#7]
请问一下，这种一般是什么问题？今天聊着聊着突然就报这个错了，难道是openai接口有消息条数限制吗？另外，能不能把具体报错信息输出到qq，这样也好知道是啥错

**Comment by PairZhu** [comment]
自己看日志，日志里有，直接输出到QQ是个不安全的行为，容易泄露隐私

**Comment by PairZhu** [comment]
不过这个日志只在控制台，没有保存到日志文件

**Comment by PairZhu** [comment]
如果你用的是第三方接口，那这个不得而知，可能性很多。如果用的openai的，那估计就是官方的限制了

**Comment by Lukangkang123** [comment]
> 不过这个日志只在控制台，没有保存到日志文件

启动Docker的控制台好像是不输出信息的，你说的是go_cqhttp的控制台日志吗？

**Comment by PairZhu** [comment]
建议学学docker... 提示：docker logs命令

**Comment by Lukangkang123** [comment]
> 自己看日志，日志里有，直接输出到QQ是个不安全的行为，容易泄露隐私



> 建议学学docker... 提示：docker logs命令

好，明天我看看。另外我想问一下，私聊能不能默认开启会话。或者配置文件里能有个参数，设置私聊默认开启会话，因为还得让别人输入#gpt begin有点小麻烦

**Comment by PairZhu** [comment]
仔细看文档，早就加了这个功能了

**Comment by Lukangkang123** [comment]
> 仔细看文档，早就加了这个功能了

我刚看了，在docker-compose.yml文件里并没有配置自动会话的参数，请问是需要手工添加进去吗？

**Comment by PairZhu** [comment]
请先了解了解docker和docker-compose

**Comment by PairZhu** [comment]
或者按照文档提示在配置文件里加也行

**Comment by Lukangkang123** [comment]
> 或者按照文档提示在配置文件里加也行

好，明天我直接在文档里添加试试

**Comment by saika2077** [comment]
我也突然报错了，网络环境确定没问题，用的官方接口，一直报错400，我重新注册了一个OpenAI账号，用新的api也一样报错400。是不是OpenAI那边官方接口有问题了

**Comment by PairZhu** [comment]
看命令行日志

**Comment by PairZhu** [comment]
我这里没遇到，会不会是网络环境的问题

**Comment by PairZhu** [comment]
指的不是连不上openai，而是ip被拉黑了

**Comment by Lukangkang123** [comment]
> 我也突然报错了，网络环境确定没问题，用的官方接口，一直报错400，我重新注册了一个OpenAI账号，用新的api也一样报错400。是不是OpenAI那边官方接口有问题了

我也报的400，不过我重启之后就好了，不知道是啥问题

**Comment by saika2077** [comment]
> 

我换了个ip重新部署，也好了。另外，不知道为什么每隔一段时间就会报错401/500，终止node进程再重新启动机器人之后又会恢复。

**Comment by Lukangkang123** [comment]
> > 
> 
> 我换了个ip重新部署，也好了。另外，不知道为什么每隔一段时间就会报错401/500，终止node进程再重新启动机器人之后又会恢复。

确实，我也是这样，每隔一段时间就出错，重启之后又马上恢复。不知道是哪里的问题。我准备用多个api-key试试。

**Comment by saika2077** [comment]
> 

我换了个ip重新部署，也好了。另外，不知道为什么每隔一段时间就会报错401/500，终止node进程再重新启动机器人之后又会恢复。

> > > 
> > 
> > 
> > 我换了个ip重新部署，也好了。另外，不知道为什么每隔一段时间就会报错401/500，终止node进程再重新启动机器人之后又会恢复。
> 
> 确实，我也是这样，每隔一段时间就出错，重启之后又马上恢复。不知道是哪里的问题。我准备用多个api-key试试。

我是源码部署的，我直接加了个定期关闭node进程再重启机器人的脚本在里面，凑合用

**Comment by Lukangkang123** [comment]
> > 
> 
> 我换了个ip重新部署，也好了。另外，不知道为什么每隔一段时间就会报错401/500，终止node进程再重新启动机器人之后又会恢复。
> 
> > > > 
> > > 
> > > 
> > > 我换了个ip重新部署，也好了。另外，不知道为什么每隔一段时间就会报错401/500，终止node进程再重新启动机器人之后又会恢复。
> > 
> > 
> > 确实，我也是这样，每隔一段时间就出错，重启之后又马上恢复。不知道是哪里的问题。我准备用多个api-key试试。
> 
> 我是源码部署的，我直接加了个定期关闭node进程再重启机器人的脚本在里面，凑合用

那你可以报错了之后自动让它重启

**Comment by Lukangkang123** [comment]
> > 
> 
> 我换了个ip重新部署，也好了。另外，不知道为什么每隔一段时间就会报错401/500，终止node进程再重新启动机器人之后又会恢复。
> 
> > > > 
> > > 
> > > 
> > > 我换了个ip重新部署，也好了。另外，不知道为什么每隔一段时间就会报错401/500，终止node进程再重新启动机器人之后又会恢复。
> > 
> > 
> > 确实，我也是这样，每隔一段时间就出错，重启之后又马上恢复。不知道是哪里的问题。我准备用多个api-key试试。
> 
> 我是源码部署的，我直接加了个定期关闭node进程再重启机器人的脚本在里面，凑合用

或者你改用第三方api试试

**Comment by saika2077** [comment]
> 

第三方api太慢了，报错更严重。定时重启基本上已经满足需求了。要是能不报错更好😂

**Comment by Lukangkang123** [comment]
> > 
> 
> 第三方api太慢了，报错更严重。定时重启基本上已经满足需求了。要是能不报错更好😂

我这边今天用的三方api的速度还可以，今天还没出现报错。过段时间看看稳定性，反正能用就行

**Comment by PairZhu** [comment]
> > 
> 
> 第三方api太慢了，报错更严重。定时重启基本上已经满足需求了。要是能不报错更好😂

我这里从来没遇到过你们的现象，我觉得大概率是网络环境问题

**Comment by Lukangkang123** [comment]
> > > 
> > 
> > 
> > 第三方api太慢了，报错更严重。定时重启基本上已经满足需求了。要是能不报错更好😂
> 
> 我这里从来没遇到过你们的现象，我觉得大概率是网络环境问题

有可能是你用了多个api-key。我今天换成多个api-key后，很明显地看到，当它发生401或者500错误时，切换到下一个api-key就能正常回复了

**Comment by PairZhu** [comment]
我这个apikey回滚算法确实做的不太好，我改一下，可能是第一个apikey因为特殊情况失败了一次，切换到了后面的apikey，之后只有报错一次之后才可能回到第一个apikey，我去优化一下

**Comment by PairZhu** [comment]
已优化，请重新拉取源码或镜像后重试

**Comment by Lukangkang123** [comment]
> 已优化，请重新拉取源码或镜像后重试

这么快改好了，我去试试

**Comment by PairZhu** [comment]
不过你单个api-key的情况还是不会好转的，所以建议多放几个apikey

**Comment by Lukangkang123** [comment]
> 不过你单个api-key的情况还是不会好转的，所以建议多放几个apikey

我放了七个apikey，今天下午用到了第三个，之后竟然连续尝试了五个apikey都失败，最后还是重启大法解决的。

**Comment by PairZhu** [comment]
你这个情况确实很怪，我一共就放了三四个apikey。而且报错报的是网络错误，理论上不应该重启解决。重启的唯一作用就是让当前使用的apikey恢复到第一个apikey，如果是因为后面的apikey失效导致的，那应该只有一次回答出错，当你哪怕不重启直接重问应该也会解决

**Comment by Lukangkang123** [comment]
> 你这个情况确实很怪，我一共就放了三四个apikey。而且报错报的是网络错误，理论上不应该重启解决。重启的唯一作用就是让当前使用的apikey恢复到第一个apikey，如果是因为后面的apikey失效导致的，那应该只有一次回答出错，当你哪怕不重启直接重问应该也会解决

在你这个更新之前，后面的apikey都失效了不会跑到第一个再循环判断，所以后面的都失效了就直接报错了，实际上第一个apikey有效。不过哪一个apikey失效，感觉有一定随机性。

**Comment by PairZhu** [comment]
对啊，但是只要报错一次之后就会跑回第一个了

**Comment by PairZhu** [comment]
所以完全没有重启的必要

**Comment by Lukangkang123** [comment]
> 对啊，但是只要报错一次之后就会跑回第一个了

这个不是你半小时前的更新刚加的吗？之前的代码，后面的报错了不会回到第一个

**Comment by PairZhu** [comment]
会的，只是不会自动回到，而是报错之后qq提醒了之后，你再试一次就回自动回到了

**Comment by Lukangkang123** [comment]
> 会的，只是不会自动回到，而是报错之后qq提醒了之后，你再试一次就回自动回到了

哦哦，那这次更新之后，一般情况下应该不会在qq输出报错了，而是在自动在所有api-key中寻找有效的。

**Comment by PairZhu** [comment]
是的，这次会保证每个apikey都会试到一遍

**Comment by saika2077** [comment]
> 是的，这次会保证每个apikey都会试到一遍

能不能加一个机器人启动时检测并自动更新的功能😂
