### ISSUE TITLE
如何取消(对话已达到最大长度，将删除最早的一条对话)这个提示？

### ISSUE THREAD

**Issue by JikeGeek** [PairZhu/GPT-QQRobot#9]
如题，每次多问几句就会提示(对话已达到最大长度，将删除最早的一条对话)请问如何取消这个提示？

**Comment by PairZhu** [comment]
你只是希望删除提示吗？还是什么

**Comment by JikeGeek** [comment]
我希望删除这个提示，不需要这个功能！

**Comment by JikeGeek** [comment]
您好，我期望删除这个提示，如果能实现还请说明！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PairZhu/GPT-QQRobot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月12日(星期天) 下午5:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PairZhu/GPT-QQRobot] 如何取消(对话已达到最大长度，将删除最早的一条对话)这个提示？ (Issue #9)





 
你只是希望删除提示吗？还是什么

**Comment by PairZhu** [comment]
我可以考虑增加一个配置选项，允许取消这个提示

**Comment by JikeGeek** [comment]
好的，感谢您的努力！期待~！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PairZhu/GPT-QQRobot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月12日(星期天) 晚上6:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PairZhu/GPT-QQRobot] 如何取消(对话已达到最大长度，将删除最早的一条对话)这个提示？ (Issue #9)





 
我可以考虑增加一个配置选项，允许取消这个提示

**Comment by PairZhu** [comment]
已更新，请看配置文档
